### PR TITLE
[new feature] Add albumentation

### PR DESCRIPTION
**Pull request by 24hours**

### CODE REVIEW

**Comment by xvjiarui** [comment]
Hi @24hours 
Thanks for the contribution. And sorry for the late reply. Since Albu is not a requirement of our repo, we may make it none by default. We may have something like [this](https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/mmdet/datasets/pipelines/transforms.py#L17-L22).

**Comment by 24hours** [comment]
Hi, 

> Hi @24hours
> Thanks for the contribution. And sorry for the late reply. Since Albu is not a requirement of our repo, we may make it none by default. We may have something like [this](https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/mmdet/datasets/pipelines/transforms.py#L17-L22).

I have made the relevant change, please check.

**Comment by maisonhai3** [comment]
> Hi @24hours
> Thanks for the contribution. And sorry for the late reply. Since Albu is not a requirement of our repo, we may make it none by default. We may have something like [this](https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/mmdet/datasets/pipelines/transforms.py#L17-L22).

I think it better we have albumentation already implanted in mmsegmentation,
make it ready-to-use,
than making users manually copy-pasted pieces code from mmdetection.

**Comment by Junjun2016** [comment]
Hi @24hours 
Thanks for your contribution.
Please fix the conflicts.

**Comment by xiexinch** [comment]
https://github.com/open-mmlab/mmsegmentation/pull/2710

**Pull request closed without merging**
