### PR TITLE
Merge the large-scale semantic segmentation dataset Imagenet-S

### PR DESCRIPTION
**Pull request by gasvn**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Based on the ImageNet dataset, we propose the ImageNet-S dataset has 1.2 million training images and 50k high-quality semantic segmentation annotations to support unsupervised/semi-supervised semantic segmentation on the ImageNet dataset.

We add the dataset and baseline performance using the vit model.

paper:
Large-scale Unsupervised Semantic Segmentation (TPAMI 2022)
[Paper link](https://arxiv.org/abs/2106.03149)

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by MengzhangLI** [comment]
Hi, shanghua, thanks for your warm-hearted PR.

Congrats for TPAMI acceptance. It is a very interesting and illuminating work.

We would review this PR asap.

Best,

**Comment by lzyhha** [comment]
When will this PR be reviewed? @MengzhangLI

**Comment by MengzhangLI** [comment]
> When will this PR be reviewed? @MengzhangLI

Hi, sorry for late reply.

We would review this PR as soon as possible (next week). In the last few weeks, my colleagues were suffered from COVID virus so many PRs and issues were accumulated. We would continue to work after new year vacation.

Best,

**Comment by lzyhha** [comment]
The weights and logs [drive](https://drive.google.com/drive/folders/1mCRmkzCJw6zPMIvZi81GIosfSpsbVqwt?usp=share_link)

**Comment by lzyhha** [comment]
Hi, what's the plan to review this PR?

**Pull request closed without merging**
