### PR TITLE
[Fix] Replace interpolate with resize

### PR DESCRIPTION
**Pull request by mmeendez8**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

I am having problems to export mmsegmentation -> onnx -> tensorflow. There is a know limitation related with interpolate (see [here](https://github.com/onnx/onnx-tensorflow/issues/632#issuecomment-743717023)). I tried to fix mmseg.ops.resize behavior to always use `align_corners` but I realize some modules are still using torch `F.interpolate`. 
`
## Modification

Use mmseg resize wrapper for all operations.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by mmeendez8** [comment]
Just realized my problem was also related with [FPN Upsample]. 

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/fpn_head.py#L48

I wonder if we should replace this calls with upsample wrapper from ops:
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/ops/wrappers.py#L29

**Comment by Junjun2016** [comment]
Hi @mmeendez8 
Thanks for your nice PR!

> I wonder if we should replace this calls with upsample wrapper from ops:
> https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/ops/wrappers.py#L29

Yes, we can replace it with upsample wrapper.
Update it, please!

**Comment by Junjun2016** [comment]
Hi @grimoire and @AllentDan

> I am having problems to export mmsegmentation -> onnx -> tensorflow. There is a know limitation related with interpolate (see here). I tried to fix mmseg.ops.resize behavior to always use align_corners but I realize some modules are still using torch F.interpolate.

**Comment by mmeendez8** [comment]
> Hi @grimoire and @AllentDan
> 
> > I am having problems to export mmsegmentation -> onnx -> tensorflow. There is a know limitation related with interpolate (see here). I tried to fix mmseg.ops.resize behavior to always use align_corners but I realize some modules are still using torch F.interpolate.

Sorry, forgot to say that problem has been fixed. Tensorflow does not support `torch.interpolate` or `torch.upsample` when `align_corners=False`. So I basically fixed `mmseg.ops.resize`behavior to always use `align_corners`, that's when I realize there was mixed calls to pytorch and mmseg.ops.

**Comment by Junjun2016** [comment]
> > Hi @grimoire and @AllentDan
> > > I am having problems to export mmsegmentation -> onnx -> tensorflow. There is a know limitation related with interpolate (see here). I tried to fix mmseg.ops.resize behavior to always use align_corners but I realize some modules are still using torch F.interpolate.
> 
> Sorry, forgot to say that problem has been fixed. Tensorflow does not support `torch.interpolate` or `torch.upsample` when `align_corners=False`. So I basically fixed `mmseg.ops.resize`behavior to always use `align_corners`, that's when I realize there was mixed calls to pytorch and mmseg.ops.

I see, thanks again!

**Comment by Junjun2016** [comment]
@mmeendez8 

> fixed `mmseg.ops.resize` behavior to always use `align_corners`

I am confused about this since he defaults `args` of `resize` are the same as `F.interpolate`.
The default setting of `align_corners` is `None`.

**Comment by Junjun2016** [comment]
Hi @mmeendez8 
Please fix the CI.

**Comment by Junjun2016** [comment]
image

Please fix the unittest of `test_interp_conv` in `test_unet.py`.

**Comment by mmeendez8** [comment]
> Hi @mmeendez8
> Please fix the CI.

Yes, sorry. I had already pushed fix

**Comment by Junjun2016** [comment]
> @mmeendez8
> 
> > fixed `mmseg.ops.resize` behavior to always use `align_corners`
> 
> I am confused about this since he defaults `args` of `resize` are the same as `F.interpolate`.
> The default setting of `align_corners` is `None`.

Could you please explain it?

**Comment by Junjun2016** [comment]
> > Hi @mmeendez8
> > Please fix the CI.
> 
> Yes, sorry. I had already pushed fix

Thanks.

**Comment by Junjun2016** [comment]
> @mmeendez8
> 
> > fixed `mmseg.ops.resize` behavior to always use `align_corners`
> 
> I am confused about this since he defaults `args` of `resize` are the same as `F.interpolate`.
> The default setting of `align_corners` is `None`.

You mean set `align_corners` to `True` or `False` instead of `None`.

**Comment by mmeendez8** [comment]
> > @mmeendez8
> > > fixed `mmseg.ops.resize` behavior to always use `align_corners`
> > 
> > 
> > I am confused about this since he defaults `args` of `resize` are the same as `F.interpolate`.
> > The default setting of `align_corners` is `None`.
> 
> You mean set `align_corners` to `True` or `False` instead of `None`?

I meant that I brute force `align_corners=True`. But I realized that this was not working properly, that's how I discover that nn.interpolate was being called in multiple places. Hope this can clarify it!

**Comment by Junjun2016** [comment]
> > > @mmeendez8
> > > > fixed `mmseg.ops.resize` behavior to always use `align_corners`
> > > 
> > > 
> > > I am confused about this since he defaults `args` of `resize` are the same as `F.interpolate`.
> > > The default setting of `align_corners` is `None`.
> > 
> > 
> > You mean set `align_corners` to `True` or `False` instead of `None`?
> 
> I meant that I brute force `align_corners=True`. But I realized that this was not working properly, that's how I discover that nn.interpolate was being called in multiple places. Hope this can clarify it!

OK, I see, thanks!

**Review by Junjun2016 — APPROVED** [review]
LGTM

**Pull request merged**
