### PR TITLE
添加CRF模块

### PR DESCRIPTION
**Pull request by 459737087**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

由于没有后处理操作，所以添加了crf，尝试提高模型的准确率

## Modification

1.首先添加了CRF模块
2.添加了pspcrf网络模型，主要就是将crf加在了pspnet的输出，也可以看作后处理操作

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

### CODE REVIEW

**Comment by MengzhangLI** [comment]
Hi, thanks for your pr.

We would review it as soon as possible.

By the way, do you have some numerical results especially with and without CRF module? 

Best,

**Comment by 459737087** [comment]
pspCRF_result
pspnet_result

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/775

**Comment by Junjun2016** [comment]
Hi @459737087 
Please remove the dataset.

**Comment by Junjun2016** [comment]
> pspCRF_result
> 这个是pspcrf的运行结果
> pspnet_result
> 这个是pspnet的运行结果
> 二者在相同的情况下跑的结果，两万次迭代
> @MengzhangLI

Which configs did you run?

**Comment by 459737087** [comment]
> > pspCRF_result
> > 这个是pspcrf的运行结果
> > pspnet_result
> > 这个是pspnet的运行结果
> > 二者在相同的情况下跑的结果，两万次迭代
> > @MengzhangLI
> 
> Which configs did you run?

I run it in pspnet_r50-d8_480x350_20k_camvid.py
in Camvid dataset

**Comment by 459737087** [comment]
> Hi @459737087
> Please remove the dataset.

where is the dataset?

**Comment by Junjun2016** [comment]
> > Hi @459737087
> > Please remove the dataset.
> 
> where is the dataset?

You have pushed the dataset to this PR.

**Comment by Junjun2016** [comment]
> > > pspCRF_result
> > > 这个是pspcrf的运行结果
> > > pspnet_result
> > > 这个是pspnet的运行结果
> > > 二者在相同的情况下跑的结果，两万次迭代
> > > @MengzhangLI
> > 
> > 
> > Which configs did you run?
> 
> I run it in pspnet_r50-d8_480x350_20k_camvid.py
> in Camvid dataset

Could you please provide some results for our supported datasets?
And could you please make a PR for Camvid dataset?

**Comment by Junjun2016** [comment]
Hi @459737087 
Please remove the dataset, you can check added files in `files changed`.

**Comment by 459737087** [comment]
> Hi @459737087
> Please remove the dataset, you can check added files in `files changed`.

ok I'll remove it

**Comment by 459737087** [comment]
no
I have no idea

**Comment by 459737087** [comment]
When I  change my code in flake8, It reports my layout goes wrong.
But I can't change it ,I look up other dataset layout. we are the same

**Comment by Junjun2016** [comment]
Hi @459737087 
The MMSeg team will discuss how to support CRF in the following release.

**Comment by 459737087** [comment]
Hi @Junjun2016 
Can I push the code?

**Review by Junjun2016 — COMMENTED** [review]
Discard the changes of `demo/MMSegmentation_Tutorial.ipynb` and `demo/inference_demo.ipynb`.

**Comment by Junjun2016** [comment]
Hi @459737087 
Could you please create a NEW PR?

**Comment by 459737087** [comment]
ok,Do you mean to add pspnet_crf block?

**Comment by Junjun2016** [comment]
> ok,Do you mean to add pspnet_crf block? @Junjun2016

Yes, now we do not have a postprocessing pipeline in mmseg.
We are thinking about how to add a postprocessing pipeline to mmseg more elegant and general (compatible with CRF, segfix, and so on), can build postprocessing from configs like backbone or decode_head.

**Comment by 459737087** [comment]
fine! @Junjun2016

**Comment by aymanaboghonim** [comment]
@459737087 could you help me implement crf ??

**Comment by OpenMMLab-Coodinator** [comment]
Hi @459737087  ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) , where you can share your experiences, ideas, and build connections with like-minded peers. 

To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Comment by aymanaboghonim** [comment]
@459737087 I hope you can add it because I want to use it .

**Comment by endaoguansanlu** [comment]
@>459737087 Hello, I also want to use crf, can you give me some guidance? Thank you and looking forward to your reply!

**Comment by endaoguansanlu** [comment]
> Yeah, are you going to add it? @aymanaboghonim

Hello, I also want to use crf, can you give me some guidance? Thank you and looking forward to your reply!

**Comment by endaoguansanlu** [comment]
@459737087 Hello, I also want to use crf, can you give me some guidance? Thank you and looking forward to your reply!

**Pull request closed without merging**
