### PR TITLE
[Enchance] support infererence with padding

### PR DESCRIPTION
**Pull request by FreyWang**
- Before padding
飞书20220522-190911
-  After padding
飞书20220522-190917

## Motivation

I use mmseg to train my model and found the mask has a left offset to the image. Finally I found that it is caused by inference input without padding. For example, A input with origin shape (1920, 1080) and `img_scale=(2048, 512)` will be resized to `(910 , 512)`.   When infer it with resnet50-d8，the final feature map is 114 * 64 and then resize it to 910*512. Attention that 114x8=912. So it is same with pad the input to (912, 512) and resize feature to (910, 512). With 2-pixel left offset

## BC-breaking (Optional)
Attention that when `dict(type='Pad', size_divisor=32),` is add, the model performance will intend to be improved, I have test several mIoU rise
- `configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_80k_ade20k.py`
from 42.72 to 42.78
- `configs/ocrnet/ocrnet_hr18s_512x512_80k_ade20k.py`
from 35.06 to 35.53
- `configs/knet/knet_s3_upernet_swin-l_8x2_512x512_adamw_80k_ade20k.py`
from 52.05 to 52.61

## Use cases (Optional)
Add `Pad` when inference to make sure that input can be divide to model stride.
[Update]
Attention that `Pad` must behinde `RandomFlip` when flip is True

```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Pad', size_divisor=32),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

### CODE REVIEW

**Comment by FreyWang** [comment]
It may effect pytorch2onnx and i will refactor the code later

**Comment by MeowZheng** [comment]
Please take a look @linfangjian01  and test pspnet and deeplabv3 performance on ADE and cityscapes with this modification.

**Review by MeowZheng — COMMENTED** [review]
@FreyWang have you compared the model performance before and after this modification? Would you like to share the results with us? Thank you

**Comment by linfangjian01** [comment]
Thx, I will do some experiments in the next two days to verify.

**Comment by FreyWang** [comment]
> @FreyWang have you compared the model performance before and after this modification? Would you like to share the results with us? Thank you
I only test several model such as deeplabv3+，ocrnet, knet and setr,  all gain 0~0.5 mIoU improve.  🥲 Test all config is difficult, some automated scripts is needed
Attention that Pad must behinde RandomFlip when flip is True

**Comment by FreyWang** [comment]
> a

the performance is same after this commit if pad is not add to config

**Comment by FreyWang** [comment]
> > > @FreyWang have you compared the model performance before and after this modification? Would you like to share the results with us? Thank you
> > > I only test several model such as deeplabv3+，ocrnet, knet and setr,  all gain 0~0.5 mIoU improve.  smiling_face_with_tear Test all config is difficult, some automated scripts is needed
> > > Attention that Pad must behinde RandomFlip when flip is True
> 
> would you like to present the TTA result with pad and without pad of deeplabv3+?

`configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_80k_ade20k.py`
from 42.72 to 42.78 after pad is added.
emmm, what is the meaning of TTA. I have only ade20k dataset now

**Comment by FreyWang** [comment]
@MeowZheng

**Comment by FreyWang** [comment]
@MeowZheng  after pad
`configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_80k_ade20k.py`  
default: 42.72 -> 42.78
ms+flip: 43.75->43.77
`configs/setr/setr_mla_512x512_160k_b8_ade20k.py`  
default: 47.34->47.58
ms+flip: 49.05->49.06

**Review by MeowZheng — APPROVED** [review]

**Pull request merged**
