### PR TITLE
[Docs] add deeplabv3 model structure

### PR DESCRIPTION
**Pull request by BLUE-coconut**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by RangeKing** [comment]
1. 图中模块里相同类型的字体类型和字体颜色要统一（例如maxpool2d里的就不符合）
2. 注意各种对齐，具体见下图
image

**Comment by BLUE-coconut** [comment]
已修改

**Comment by BLUE-coconut** [comment]
deeplabv3_r50-d8_structure_01(7)
已修改

**Review by MeowZheng — COMMENTED** [review]
please solve the conflict

**Review by RangeKing — APPROVED** [review]
LGTM

**Review by MeowZheng — APPROVED** [review]

**Pull request merged**
