### PR TITLE
Update get_flops.py

### PR DESCRIPTION
**Pull request by kinglintianxia**
argparse.ArgumentParser(description='Get the FLOPs of a segmentor')

### CODE REVIEW

**Review by MeowZheng — APPROVED** [review]
Many thanks for your contribution. It looks good to me.

**Comment by MeowZheng** [comment]
Might fix lint problem.

**Comment by kinglintianxia** [comment]
> Might fix lint problem.

**Comment by kinglintianxia** [comment]
I have fix the lint error

**Pull request merged**
